name: lanepilot

services:
  raspberrypi:
    container_name: raspberrypi
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot/raspberrypi:latest
    environment:
      - DEVICE_STATIC_IP=192.168.100.1
      - UDP_PORT=8000
      - TCP_PORT=8001
      - HANDSHAKE_SECRET=default_password_1234 # Change this to a secure password
    network_mode: host
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "3"