name: lanepilot

services:
  raspberrypi:
    container_name: raspberrypi
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot/raspberrypi:latest
    environment:
      - DEVICE_STATIC_IP=192.168.100.1
      - GSTREAMER_PORT=8000
      - ZMQ_PORT=8001
      - DISPLAY_SERVER_PORT=8002
      - HANDSHAKE_SECRET=default_password_1234 # Change this to a secure password
      - HOTSPOT_IP=192.168.100.50
      - HOTSPOT_SSID=LanePilot
      - HOTSPOT_PASSWORD=default_password_1234 # Change this to a secure password
    network_mode: host
    volumes:
      - /proc/device-tree/model:/proc/device-tree/model:ro
      - /boot/firmware/config.txt:/boot/firmware/config.txt:ro
    group_add:
      - dialout
      - gpio
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/gpiomem0:/dev/gpiomem0
      - /dev/gpiochip0:/dev/gpiochip0
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_RAWIO
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "3"