services:
  jetson:
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot:jetson-latest
    network_mode: host
    runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
