name: lanepilot

services:
  jetson:
    container_name: jetson
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot/jetson:latest
    environment:
      - DEVICE_STATIC_IP=192.168.100.2
      - UDP_PORT=8000
      - TCP_PORT=8001
    network_mode: host
    cap_add:
      - NET_ADMIN
    runtime: nvidia
    gpus: all
    volumes:
      - /usr/lib/aarch64-linux-gnu:/hostlibs:ro
      - /usr/local/cuda:/usr/local/cuda:ro
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "3"
