name: lanepilot

services:
  jetson:
    container_name: jetson
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot/jetson:latest
    environment:
      - DEVICE_STATIC_IP=192.168.100.2
      - GSTREAMER_PORT=8000
      - ZMQ_PORT=8001
      - HANDSHAKE_SECRET=default_password_1234 # Change this to a secure password
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    runtime: nvidia
    gpus: all
    volumes:
      - /usr/lib/aarch64-linux-gnu:/hostlibs/all:ro
      - /usr/local/cuda:/hostlibs/cuda:ro
      - /proc/device-tree/model:/proc/device-tree/model:ro
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "3"
