name: lanepilot

services:
  jetson:
    container_name: jetson
    restart: always
    platform: linux/arm64
    image: ghcr.io/appsolves/lanepilot/jetson:latest
    network_mode: host
    runtime: nvidia
    gpus: all
    volumes:
      - /usr/lib/aarch64-linux-gnu:/hostlibs:ro
      - /usr/local/cuda:/usr/local/cuda:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
