name: Build & Push Docker Images to GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Save lowercase owner and repository names
        id: save-vars
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update apt packages and install qemu
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y make ninja-build libpixman-1-dev libglib2.0-dev
          git clone https://gitlab.com/qemu-project/qemu.git
          cd qemu
          ./configure \
            --target-list=aarch64-linux-user \
            --static \
            --enable-linux-user \
            --disable-system \
            --disable-tools \
            --disable-docs \
            --prefix=/opt/qemu-arm64

          make -j$(nproc)
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
          cd ..
          rm -rf ./qemu

      - name: Copy .dockerignore file
        run: |
          for dir in firmware/*/; do
            cp .dockerignore "$dir"
          done

      - name: Build and push Docker image for Raspberry Pi
        run: |
          cd firmware/raspberrypi
          docker buildx build --platform linux/arm64 --build-context root=../../ -f Dockerfile.raspberrypi \
            -t ghcr.io/${{ steps.save-vars.outputs.repository }}/raspberrypi:latest \
            -t ghcr.io/${{ steps.save-vars.outputs.repository }}/raspberrypi:${{ github.ref_name }} .
          docker push ghcr.io/${{ steps.save-vars.outputs.repository }}/raspberrypi:latest
          docker push ghcr.io/${{ steps.save-vars.outputs.repository }}/raspberrypi:${{ github.ref_name }}

      - name: Build and push Docker image for Jetson Linux
        run: |
          cd firmware/jetson
          docker buildx build --platform linux/arm64 --build-context root=../../ --build-context models=../../assets/trained_models \
            -f Dockerfile.jetson \
            -t ghcr.io/${{ steps.save-vars.outputs.repository }}/jetson:latest \
            -t ghcr.io/${{ steps.save-vars.outputs.repository }}/jetson:${{ github.ref_name }} .
          docker push ghcr.io/${{ steps.save-vars.outputs.repository }}/jetson:latest
          docker push ghcr.io/${{ steps.save-vars.outputs.repository }}/jetson:${{ github.ref_name }}