name: Build & Push Docker Images to GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update apt packages and install qemu
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y make ninja-build libpixman-1-dev
          git clone https://gitlab.com/qemu-project/qemu.git
          cd qemu
          ./configure
          make
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
          cd ..
          rm -rf ./qemu

      - name: Copy .dockerignore file
        run: |
          for dir in firmware/*/; do
            cp .dockerignore "$dir"
          done

      - name: Build and push Docker image for Raspberry Pi
        run: |
          cd firmware/raspberry
          docker buildx build --platform linux/arm64 --build-context root=../../ --build-context models=../../assets/trained_models -f Dockerfile.raspberry \
            -t ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberrypi-latest \
            -t ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberrypi-${{ github.ref_name }} .
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberrypi-latest
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberrypi-${{ github.ref_name }}

      - name: Build and push Docker image for Jetson Linux
        run: |
          cd ../jetson
          docker buildx build --platform linux/arm64 --build-context root=../../ -f Dockerfile.jetson \
            -t ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-latest \
            -t ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-${{ github.ref_name }} .
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-latest
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-${{ github.ref_name }}