name: Build & Push Docker Images to GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push-raspberry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy .dockerignore file
        run: |
          for dir in firmware/*/; do
            cp .dockerignore "$dir"
          done

      - name: Change directory to firmware
        run: cd firmware/raspberry

      - name: Build Docker image for Raspberry
        run: |
          docker build --build-context root=../../ -f Dockerfile.raspberry -t ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberry-latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:raspberry-latest

  build-and-push-jetson:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy .dockerignore file
        run: |
          for dir in firmware/*/; do
            cp .dockerignore "$dir"
          done

      - name: Change directory to firmware
        run: cd firmware/jetson

      - name: Build Docker image for Jetson
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f Dockerfile.jetson \
            -t ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-latest \
            --build-context root=../../ .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:jetson-latest